project:
  type: website

website:
  title: "Andy Ho"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true



